from enum import Enum
from pydantic import BaseModel


class ResponseModel(BaseModel):
    retcode: int
    retmsg: dict


class Label(Enum):
    Sexy = "性感"
    Terror = "暴恐"
    Illegal = "违法"
    Ad = "广告"
    Politics = "涉政"
    Porn = "色情"
    Abuse = "辱骂"
    Spam = "灌水"


class SubLabel(Enum):
    WomenSexyLeg = "女性性感腿"
    WomenSexy = "女性性感着装"
    MenSexy = "男性性感着装"
    WomenSexyBack = "女性性感背部"
    WomenSexyChest = "女性性感胸部"
    ACGSexy = "ACG性感"
    MiddleFinger = "中指"
    Kiss = "亲吻"
    HipCloseUp = "臀部特写"
    ChestCloseUp = "胸部特写"
    FootCloseUp = "脚部特写"
    CrotchCloseUp = "亲密行为"
    SexySum = "全局性感"
    VulgarLeg = "低俗腿部"
    VulgarChest = "低俗胸部"
    Burka = "特殊服饰"
    Uniform = "军警制服"
    Gun = "枪支等热武器"
    BigWeapon = "军事武器"
    Knife = "刀具等冷兵器"
    Crowd = "人群聚集"
    Blood = "血腥画面"
    Fire = "火灾"
    ACGTerror = "ACG暴恐"
    Horror = "恐怖画面"
    Smoking = "吸烟"
    Drink = "饮酒"
    CarLive = "车内直播"
    BedLive = "床上直播"
    Drug = "毒品"
    Gambling = "赌博"
    Fight = "打斗"
    Tattoo = "纹身"
    Contraband = "违禁品"
    QrCode = "二维码"
    AppLogo = "应用图标"
    MovieLogo = "电影图标"
    CCTVLogo = "央视台标"
    LocalTVLogo = "地方台标"
    ForeignVideoAppLogo = "境外视频应用"
    OlympicsLogo = "奥运会"
    ForeignTVLogo = "境外电视台标"
    Phone = "手机"
    NationalOfficial = "国家领导人"
    ProvincialOfficial = "省部级领导人"
    CountryOfficial = "市县级领导人"
    TWOfficial = "台湾地区领导人"
    HKOfficial = "港澳地区领导人"
    MacaoOfficial = "港澳地区领导人"
    Martyrs = "革命烈士"
    ChinesePresident = "中国国家主席"
    MainlandIllegalOfficial = "境内违法领导人"
    MainlandOfficialRelative = "境内领导人亲属"
    AntiParty = "反党人士"
    Splitter = "分裂分子"
    NaziCriminal = "纳粹战犯"
    WarCriminal = "侵华战犯"
    HistoricalPerson = "历史人物"
    Terrorist = "恐怖分子头目"
    Cult = "邪教组织人物"
    ForeignOfficial = "海外政治人物"
    BadStar = "劣迹明星"
    Inferior = "劣迹网红"
    PolityLogo = "政治实体"
    SensitivePolityLogo = "负面政治实体"
    TianAnMen = "天安门"
    RMYXJiNianBei = "人民英雄纪念碑"
    RenMinDaHuiTang = "人民大会堂"
    HuaBiao = "华表"
    MinZhuNvShengXiang64 = "民主女神像"
    LadyLibertyHK = "香港民主女神像"
    JingGuoShengShe = "靖国神社"
    WeiLingTa = "慰灵塔"
    FengTianZhongLingTa = "奉天忠灵塔"
    GuoShangZhiZhu = "国殇之柱"
    MinZhuLieShiBei = "民主烈士纪念碑"
    _64JiNianBei = "64纪念碑"
    RenMinDaHuiTangInner = "人民大会堂内部"
    CCPVirus = "中共病毒"
    JingGangShanA = "井冈山A"
    JingGangShanB = "井冈山B"
    SexyBehavior = "性行为"
    WomenPrivatePart = "女性下体"
    WomenChest = "女性胸部"
    MenPrivatePart = "男性下体"
    ButtocksExposed = "臀部"
    NakedChild = "儿童裸露"
    ACGPorn = "ACG色情"
    PornSum = "全局色情"
    TouchChest = "摸胸"
    TouchHip = "摸臀"
    TouchTriangle = "摸下体"
    SM = "SM"
    Tongue = "吐舌挑逗"
    NakedAnimal = "动物裸露"
    SexAids = "性用品"


class Suggestion(Enum):
    Pass = "通过"
    Review = "疑似"
    Block = "不通过"
