import time as t

from typing import Union
from beanie import Document
from graia.ariadne.event.mirai import (
    BotOnlineEvent,
    BotOfflineEventActive,
    BotOfflineEventForce,
    BotOfflineEventDropped,
    BotReloginEvent,
    BotGroupPermissionChangeEvent,
    FriendInputStatusChangedEvent,
    FriendNickChangedEvent,
    FriendRecallEvent,
    BotMuteEvent,
    BotUnmuteEvent,
    BotJoinGroupEvent,
    BotLeaveEventActive,
    BotLeaveEventKick,
    GroupRecallEvent,
    GroupNameChangeEvent,
    GroupEntranceAnnouncementChangeEvent,
    GroupMuteAllEvent,
    GroupAllowAnonymousChatEvent,
    GroupAllowConfessTalkEvent,
    GroupAllowMemberInviteEvent,
    MemberJoinEvent,
    MemberLeaveEventKick,
    MemberLeaveEventQuit,
    MemberCardChangeEvent,
    MemberSpecialTitleChangeEvent,
    MemberPermissionChangeEvent,
    MemberMuteEvent,
    MemberUnmuteEvent,
    MemberHonorChangeEvent,
    NudgeEvent,
    NewFriendRequestEvent,
    MemberJoinRequestEvent,
    BotInvitedJoinGroupRequestEvent,
    OtherClientOnlineEvent,
    OtherClientOfflineEvent,
    CommandExecutedEvent,
)
from graia.ariadne.event.message import (
    FriendMessage,
    GroupMessage,
    TempMessage,
    OtherClientMessage,
    StrangerMessage,
    ActiveMessage,
    ActiveFriendMessage,
    FriendSyncMessage,
    ActiveGroupMessage,
    GroupSyncMessage,
    ActiveTempMessage,
    TempSyncMessage,
    ActiveStrangerMessage,
    StrangerSyncMessage,
)


class ABotEventData(Document):
    type: str
    time: int = int(t.time())
    event: Union[
        BotOnlineEvent,
        BotOfflineEventActive,
        BotOfflineEventForce,
        BotOfflineEventDropped,
        BotReloginEvent,
        BotGroupPermissionChangeEvent,
        FriendInputStatusChangedEvent,
        FriendNickChangedEvent,
        FriendRecallEvent,
        BotMuteEvent,
        BotUnmuteEvent,
        BotJoinGroupEvent,
        BotLeaveEventActive,
        BotLeaveEventKick,
        GroupRecallEvent,
        GroupNameChangeEvent,
        GroupEntranceAnnouncementChangeEvent,
        GroupMuteAllEvent,
        GroupAllowAnonymousChatEvent,
        GroupAllowConfessTalkEvent,
        GroupAllowMemberInviteEvent,
        MemberJoinEvent,
        MemberLeaveEventKick,
        MemberLeaveEventQuit,
        MemberCardChangeEvent,
        MemberSpecialTitleChangeEvent,
        MemberPermissionChangeEvent,
        MemberMuteEvent,
        MemberUnmuteEvent,
        MemberHonorChangeEvent,
        NudgeEvent,
        NewFriendRequestEvent,
        MemberJoinRequestEvent,
        BotInvitedJoinGroupRequestEvent,
        OtherClientOnlineEvent,
        OtherClientOfflineEvent,
        CommandExecutedEvent,
    ]


class ABotMessageData(Document):
    type: str
    time: int = int(t.time())
    message: Union[
        FriendMessage,
        GroupMessage,
        TempMessage,
        OtherClientMessage,
        StrangerMessage,
        ActiveMessage,
        ActiveFriendMessage,
        FriendSyncMessage,
        ActiveGroupMessage,
        GroupSyncMessage,
        ActiveTempMessage,
        TempSyncMessage,
        ActiveStrangerMessage,
        StrangerSyncMessage,
    ]
